model:
  name: 'spcb_resnet50_512'
  pretrained: True
  load_weights: ''

data:
  type: 'image'
  sources: ['kescireid']
  targets: ['kescireid']
  height: 384
  width: 128
  combineall: False
  is_train: True # train(include val) or inference. Default is True.
  transforms: ['random_flip', 'random_crop', 'random_erase', 'cutout']
  save_dir: 'log/spcb_r50_512_ibn_softmax_triplet_384x128_adam_v2.yaml'
sampler:
  train_sampler: 'RandomIdentitySampler'
loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    margin: 0.3
#    metric: 'cosine'
    weight_t: 1.  # weight to balance hard triplet loss
    weight_x: 1.0  # weight to balance cross entropy loss
train:
  optim: 'adam'
  lr: 3.5e-4
  max_epoch: 400
  batch_size: 64
  fixbase_epoch: 0
  open_layers: []
  staged_lr: False
  lr_scheduler: 'warmup_linear'
  stepsize: [150, 300]
  gamma: 0.1
  seed: 2019
  warmup_factor: 0.01
  warmup_iters: 10

test:
  batch_size: 100
#  dist_metric: 'cosine'
  normalize_feature: True
  evaluate: False # train stage
  eval_freq: 5
  rerank: False
  visactmap: False
  visrank: False  # visualize ranked results (only available when cfg.test.evaluate=True)
  visrank_topk: 20  # top-k ranks to visualize
